"""
Django settings for instructkit project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os
from .common import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS += []

# Application definition
DJANGO_APPS += []
CUSTOM_APPS += []

INSTALLED_APPS = DJANGO_APPS + CUSTOM_APPS

MIDDLEWARE += []

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8000',
    'http://localhost:9000',
    'http://127.0.0.1:9000',
    'http://127.0.0.1:3000',
    'http://localhost:3000',
)

# Database handled by django-heroku. Use for customizations only.
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# Static files (CSS, JavaScript, Images) handled by django-heroku. Use for customizations only.
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# Logging handled by django-heroku. Use for customizations only.
LOGGING = {
    'disable_existing_loggers': False,
    'version': 1,
    'formatters': {
        'short': {
            'format': '%(asctime)s %(levelname)-5s %(name)-5s %(message)s',
            'datefmt': '%Y-%m-%d'
        },
        'verbose': {
            'format': '%(asctime)s %(levelname)-8s %(name)-15s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            # logging handler that outputs log messages to terminal
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'filters': [],
            'formatter': 'short'
        },
        'file': {
            # logging handler that outputs log messages to terminal
            'class': 'logging.FileHandler',
            'level': 'DEBUG',
            'filters': [],
            'formatter': 'verbose',
            # TODO: Create a logs/ path usable by deployment user
            'filename': 'instructkit.log'
        },
    },
    'loggers': {
        '': {
            # this sets root level logger to log debug and higher level
            # logs to console. All other loggers inherit settings from
            # root level logger.
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False, # this tells logger to send logging message
                                # to its parent (will send if set to True)
        },
        'django.db': {
            # django also has database level logging
        },
    },
}

import django_heroku
django_heroku.settings(locals())
