# Generated by Django 2.0.3 on 2018-04-01 05:47

import accounts.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructor_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=accounts.models.skill_defaults),
        ),
    ]
