# Generated by Django 2.0.3 on 2018-10-25 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
