# Generated by Django 2.0.3 on 2019-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Default is days. Set to hours, weeks, months.', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Default is days. Set to hours, weeks, months.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Default is days. Set to hours, weeks, months.', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='duration',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='unit',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Default is days. Set to hours, weeks, months.', max_length=20),
        ),
    ]
